name: atonement
description: "A new Flutter project."
publish_to: 'none'
version: 0.0.1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  cupertino_icons: ^1.0.6
  google_sign_in: ^6.2.1
  flutter_smart_dialog: ^4.9.7+7
  google_sign_in_web: ^0.12.4+1
  http: ^1.2.1
  device_info_plus: ^10.1.0
  firebase_messaging: ^15.0.1
  firebase_core: ^3.1.0
  cloud_firestore: ^5.0.2
  firebase_auth: ^5.1.2
  file_picker: ^8.0.6
  firebase_storage: ^12.1.1
  boxy: ^2.2.0
  url_launcher: ^6.3.0
  framework:
    git: https://github.com/xhzq233/framework.git
  cached_network_image: ^3.4.0
  flutter_cache_manager: ^3.4.0
  firebase_crashlytics: ^4.1.0
  firebase_analytics: ^11.3.0

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^4.0.0
  build_runner: ^2.4.6

flutter:
  uses-material-design: true

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
