// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2mNHKdvZQIKNGXBeJPQV6riXnV9RGhQU',
    appId: '1:80750108764:web:93bbb279b8bff342430699',
    messagingSenderId: '80750108764',
    projectId: 'xhzq233-firebase-demo',
    authDomain: 'xhzq233-firebase-demo.firebaseapp.com',
    storageBucket: 'xhzq233-firebase-demo.appspot.com',
    measurementId: 'G-ZNR9T05ENR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-znm-cZScRI33ASKqfYKysMcqkCyXSWA',
    appId: '1:80750108764:android:73a4f196832f9c8a430699',
    messagingSenderId: '80750108764',
    projectId: 'xhzq233-firebase-demo',
    storageBucket: 'xhzq233-firebase-demo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdwLlA6fQbuz_cV2qHgVq9Har0X3UgE-s',
    appId: '1:80750108764:ios:22b737364becc187430699',
    messagingSenderId: '80750108764',
    projectId: 'xhzq233-firebase-demo',
    storageBucket: 'xhzq233-firebase-demo.appspot.com',
    iosClientId: '80750108764-1c9gmj9ds5sp85unruqgrs5j41mqgq7f.apps.googleusercontent.com',
    iosBundleId: 'xyz.xhzq.atonement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdwLlA6fQbuz_cV2qHgVq9Har0X3UgE-s',
    appId: '1:80750108764:ios:20c03a4e931003ee430699',
    messagingSenderId: '80750108764',
    projectId: 'xhzq233-firebase-demo',
    storageBucket: 'xhzq233-firebase-demo.appspot.com',
    iosClientId: '80750108764-3ue1o2tjahr6skrs168ltg9mep8ntsqn.apps.googleusercontent.com',
    iosBundleId: 'com.example.atonement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2mNHKdvZQIKNGXBeJPQV6riXnV9RGhQU',
    appId: '1:80750108764:web:176f5a70bf356af8430699',
    messagingSenderId: '80750108764',
    projectId: 'xhzq233-firebase-demo',
    authDomain: 'xhzq233-firebase-demo.firebaseapp.com',
    storageBucket: 'xhzq233-firebase-demo.appspot.com',
    measurementId: 'G-ERQ16DJSF5',
  );

}